### ISSUE TITLE
Finish Function 4 - find_best_and_worst_campaigns

### ISSUE THREAD

**Issue by beth-ouyang** [UBC-MDS/Group_9_GA_Metrics#30]
Please finish function 4:
- find_best_and_worst_campaigns
- unit test

**Comment by WeilinHan8** [comment]
Write test cases and code iteratively
Before writing any code, revisit your function specifications from last week and revise them if needed. As you do this, think critically about what function inputs you expect from the user and what your function is supposed to do (e.g., return). The function should be written defensively. That is, it should handle incorrect input and errors detected during execution via throwing exceptions with useful error messages.
Write a unit tests for each specified function, which is named after the function being tested. The unit tests should test at least 3 to 5 edge of the most important cases to ensure that the function returns what is expected to the user. It should also test for expected errors. When writing your tests, build them around your function specifications and requirements.

After writing your unit tests, write the internal code for your functions. Write function code and tests in close temporal proximity with each other. The process of writing function code and test cases will be iterative; there will be several rounds of writing tests -> function improvement -> writing more tests -> function improvement -> writing more tests
function improvement, etc. Make sure that the tests cover all code branches (e.g., if your function has an if statement, you should have tests where the if statement is true, and where the if statement is false.

As you develop your code and test cases, update your code documentation so that it makes sense with any of the changes you have made. Do not forget to also document your test functions. Check whether the code passes the unit tests you have written using the [pytest package](https://docs.pytest.org/en/latest/getting-started.html) for Python packages and [testthat](https://testthat.r-lib.org/) for R packages.
