### ISSUE TITLE
Choose a suitable license to your package and justify your choice

### ISSUE THREAD

**Issue by tangyl92** [UBC-MDS/Group_9_GA_Metrics#57]
Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice in an issue in your package repository. All team members should make meaningful contributions to this discussion in the GitHub issue.

**Comment by WeilinHan8** [comment]
I think we can continue using MIT license since this package is for convenience of everyone that work with Google Analytics data so we want to encourage others to use and improve it. The current package is still far from perfect since it only contains four functions and it need to be improved with help of other developers. As MIT is one of most permissive and commonly used license, other developers will know they are encouraged to contribute to this package when seeing the MIT license.

**Comment by beth-ouyang** [comment]
I think MIT should be fine. It’s widely used, and should be common for everyone.

**Comment by tangyl92** [comment]
I agree. The MIT License is simple and let us freely use, change, and share our software. It's widely accepted and makes combining our work with others' projects easy, appealing to both open-source communities and businesses. In real working space, usually there is legal expert to add extra contents to this license.

**Comment by ianm99** [comment]
my preference would be the GNU license; if we make our code open source, I would want all derivative works to remain open source as well. BUT I will concede to popular demand ~
